version: '3'
services:
  meuprimeirocrudgo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8080
      - MONGODB_URL=mongodb://localhost:27017
      - MONGODB_DB=crud-init
      - MONGODB_USER_DB_COLLECTION=users
      - JWT_SECRET_KEY=123$567*901@34%67*90!23$09*76%4#
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - meu_crud_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - meu_crud_network

networks:
  meu_crud_network: